//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EFX
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class INYSOFT2013Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto INYSOFT2013Entities usando la cadena de conexión encontrada en la sección 'INYSOFT2013Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public INYSOFT2013Entities() : base("name=INYSOFT2013Entities", "INYSOFT2013Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto INYSOFT2013Entities.
        /// </summary>
        public INYSOFT2013Entities(string connectionString) : base(connectionString, "INYSOFT2013Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto INYSOFT2013Entities.
        /// </summary>
        public INYSOFT2013Entities(EntityConnection connection) : base(connection, "INYSOFT2013Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vista_saldosPrestamosPersonal> vista_saldosPrestamosPersonal
        {
            get
            {
                if ((_vista_saldosPrestamosPersonal == null))
                {
                    _vista_saldosPrestamosPersonal = base.CreateObjectSet<vista_saldosPrestamosPersonal>("vista_saldosPrestamosPersonal");
                }
                return _vista_saldosPrestamosPersonal;
            }
        }
        private ObjectSet<vista_saldosPrestamosPersonal> _vista_saldosPrestamosPersonal;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vista_planillaSemanal> planillaSemanal
        {
            get
            {
                if ((_planillaSemanal == null))
                {
                    _planillaSemanal = base.CreateObjectSet<vista_planillaSemanal>("planillaSemanal");
                }
                return _planillaSemanal;
            }
        }
        private ObjectSet<vista_planillaSemanal> _planillaSemanal;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vista_saldosPrestamosPersonal. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovista_saldosPrestamosPersonal(vista_saldosPrestamosPersonal vista_saldosPrestamosPersonal)
        {
            base.AddObject("vista_saldosPrestamosPersonal", vista_saldosPrestamosPersonal);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet planillaSemanal. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToplanillaSemanal(vista_planillaSemanal vista_planillaSemanal)
        {
            base.AddObject("planillaSemanal", vista_planillaSemanal);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="INYSOFT2013Model", Name="vista_planillaSemanal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vista_planillaSemanal : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vista_planillaSemanal.
        /// </summary>
        /// <param name="pK">Valor inicial de la propiedad PK.</param>
        /// <param name="semana">Valor inicial de la propiedad semana.</param>
        public static vista_planillaSemanal Createvista_planillaSemanal(global::System.Int64 pK, global::System.String semana)
        {
            vista_planillaSemanal vista_planillaSemanal = new vista_planillaSemanal();
            vista_planillaSemanal.PK = pK;
            vista_planillaSemanal.semana = semana;
            return vista_planillaSemanal;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.Int64 _PK;
        partial void OnPKChanging(global::System.Int64 value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String semana
        {
            get
            {
                return _semana;
            }
            set
            {
                if (_semana != value)
                {
                    OnsemanaChanging(value);
                    ReportPropertyChanging("semana");
                    _semana = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("semana");
                    OnsemanaChanged();
                }
            }
        }
        private global::System.String _semana;
        partial void OnsemanaChanging(global::System.String value);
        partial void OnsemanaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detalle
        {
            get
            {
                return _detalle;
            }
            set
            {
                OndetalleChanging(value);
                ReportPropertyChanging("detalle");
                _detalle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detalle");
                OndetalleChanged();
            }
        }
        private global::System.String _detalle;
        partial void OndetalleChanging(global::System.String value);
        partial void OndetalleChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="INYSOFT2013Model", Name="vista_saldosPrestamosPersonal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vista_saldosPrestamosPersonal : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vista_saldosPrestamosPersonal.
        /// </summary>
        /// <param name="pK">Valor inicial de la propiedad PK.</param>
        public static vista_saldosPrestamosPersonal Createvista_saldosPrestamosPersonal(global::System.Int64 pK)
        {
            vista_saldosPrestamosPersonal vista_saldosPrestamosPersonal = new vista_saldosPrestamosPersonal();
            vista_saldosPrestamosPersonal.PK = pK;
            return vista_saldosPrestamosPersonal;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.Int64 _PK;
        partial void OnPKChanging(global::System.Int64 value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodPer
        {
            get
            {
                return _CodPer;
            }
            set
            {
                OnCodPerChanging(value);
                ReportPropertyChanging("CodPer");
                _CodPer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodPer");
                OnCodPerChanged();
            }
        }
        private global::System.String _CodPer;
        partial void OnCodPerChanging(global::System.String value);
        partial void OnCodPerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detalle
        {
            get
            {
                return _Detalle;
            }
            set
            {
                OnDetalleChanging(value);
                ReportPropertyChanging("Detalle");
                _Detalle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Detalle");
                OnDetalleChanged();
            }
        }
        private global::System.String _Detalle;
        partial void OnDetalleChanging(global::System.String value);
        partial void OnDetalleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.String _fecha;
        partial void OnfechaChanging(global::System.String value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String concepto
        {
            get
            {
                return _concepto;
            }
            set
            {
                OnconceptoChanging(value);
                ReportPropertyChanging("concepto");
                _concepto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("concepto");
                OnconceptoChanged();
            }
        }
        private global::System.String _concepto;
        partial void OnconceptoChanging(global::System.String value);
        partial void OnconceptoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> importe
        {
            get
            {
                return _importe;
            }
            set
            {
                OnimporteChanging(value);
                ReportPropertyChanging("importe");
                _importe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("importe");
                OnimporteChanged();
            }
        }
        private Nullable<global::System.Decimal> _importe;
        partial void OnimporteChanging(Nullable<global::System.Decimal> value);
        partial void OnimporteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> saldo
        {
            get
            {
                return _saldo;
            }
            set
            {
                OnsaldoChanging(value);
                ReportPropertyChanging("saldo");
                _saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saldo");
                OnsaldoChanged();
            }
        }
        private Nullable<global::System.Decimal> _saldo;
        partial void OnsaldoChanging(Nullable<global::System.Decimal> value);
        partial void OnsaldoChanged();

        #endregion

    
    }

    #endregion

    
}
