//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EFW
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class INYSOFT2013Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new INYSOFT2013Entities object using the connection string found in the 'INYSOFT2013Entities' section of the application configuration file.
        /// </summary>
        public INYSOFT2013Entities() : base("name=INYSOFT2013Entities", "INYSOFT2013Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new INYSOFT2013Entities object.
        /// </summary>
        public INYSOFT2013Entities(string connectionString) : base(connectionString, "INYSOFT2013Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new INYSOFT2013Entities object.
        /// </summary>
        public INYSOFT2013Entities(EntityConnection connection) : base(connection, "INYSOFT2013Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

    
}
